name: Hexo Auto Deploy

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  DeployHexo:
    runs-on: ubuntu-latest

    env:
      GPG_PRIVATE: ${{ secrets.GPG_PRIVATE }}
      GPG_PUBLIC: ${{ secrets.GPG_PUBLIC }}
      ID_RSA: ${{ secrets.ID_RSA }}
      GSC: ${{ secrets.GSC }}
      BAIDU_TOKEN: ${{ secrets.BAIDU_TOKEN }}
      BING_TOKEN: ${{ secrets.BING_TOKEN }}

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Compress Images
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          compressOnly: true
          jpegQuality: '80'
          jpegProgressive: false
          pngQuality: '80'
          webpQuality: '80'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Setup Hexo
        run: |
          npm install hexo-cli -g

      - name: Install Dependence
        run: |
          npm install

      - name: Import SSH Keys
        run: |
          mkdir -p ~/.ssh/
          echo "$ID_RSA" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa

      - name: Import GPG Keys
        run: |
          echo "$GPG_PUBLIC" > ./HBWBlog_public.asc
          gpg --import ./HBWBlog_public.asc
          echo "$GPG_PRIVATE" > ./HBWBlog_SECRET.asc
          gpg --allow-secret-key-import --import ./HBWBlog_SECRET.asc

      - name: Import Google Search Console Key File
        run: |
          echo "$GSC" > ./GSC.json

      - name: Set Git Config
        run: |
          git config --global user.signingkey 77D1E779184BB2BFB1C737B5075CA7F6CC559CC2
          git config --global init.defaultBranch main
          git config --global commit.gpgsign true
          git config --global user.email "hanbiwolf@outlook.com"
          git config --global user.name "HanBiWolf"
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Clean Public Directory
        run: |
          hexo clean

      - name: Generate Public Directory
        run: |
          hexo g

      - name: Deploy Public Directory
        run: |
          hexo deploy